-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_memories ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_chat_sessions ON chat_sessions FOR SELECT USING (true);
CREATE POLICY anon_insert_chat_sessions ON chat_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_chat_sessions ON chat_sessions FOR UPDATE USING (true);
CREATE POLICY anon_delete_chat_sessions ON chat_sessions FOR DELETE USING (true);

CREATE POLICY anon_select_chat_messages ON chat_messages FOR SELECT USING (true);
CREATE POLICY anon_insert_chat_messages ON chat_messages FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_chat_messages ON chat_messages FOR UPDATE USING (true);
CREATE POLICY anon_delete_chat_messages ON chat_messages FOR DELETE USING (true);

CREATE POLICY anon_select_ai_memories ON ai_memories FOR SELECT USING (true);
CREATE POLICY anon_insert_ai_memories ON ai_memories FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_ai_memories ON ai_memories FOR UPDATE USING (true);
CREATE POLICY anon_delete_ai_memories ON ai_memories FOR DELETE USING (true);

