/**
 * 🚨 此文件由 Meoo Cloud 自动生成，请勿手动修改！
 * This file is auto-generated by Meoo Cloud. Do not edit manually!
 */

import { Platform } from 'react-native';
import { createClient } from '@supabase/supabase-js';
import Constants from 'expo-constants';
import type { Database } from './types';

// URL polyfill 仅 Native 端需要（Web 浏览器自带 URL 实现）
if (Platform.OS !== 'web') {
  require('react-native-url-polyfill/auto');
}

/**
 * 跨端获取 Supabase URL，优先级：
 * 1. EXPO_PUBLIC_SUPABASE_URL 环境变量（构建时注入）
 * 2. Meoo Cloud 初始化时写入的公开 Cloud URL（保证 APK 离线 bundle 可用）
 * 3. app.json → extra.supabaseUrl（通过 expo-constants 读取，dev manifest 兜底）
 * 4. Web 端回退到 window.location.origin + /sb-api
 * 5. 兜底返回占位 URL（避免 createClient 崩溃），仅打印 warn
 */
const GENERATED_SUPABASE_URL = "https://mwfvhwsf69k5.meoo.info/sb-api";

export function getSupabaseUrl(): string {
  const extra = Constants.expoConfig?.extra as Record<string, unknown> | undefined;
  const url =
    process.env.EXPO_PUBLIC_SUPABASE_URL
    || GENERATED_SUPABASE_URL
    || (typeof extra?.supabaseUrl === 'string' ? extra.supabaseUrl : '');

  if (url) {
    return url.replace(/\/$/, '');
  }

  // Web 端回退：使用页面 origin + /sb-api
  if (Platform.OS === 'web' && typeof window !== 'undefined' && window.location) {
    return `${window.location.origin}/sb-api`;
  }

  // Native 端未配置：warn 而非 throw，避免 RedBox 崩溃
  console.warn(
    '[Cloud] Supabase URL is not configured. ' +
    'Set EXPO_PUBLIC_SUPABASE_URL or expo.extra.supabaseUrl.'
  );
  return 'http://placeholder.invalid';
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg0MjQ4ODUwLCJleHAiOjEzMjk0ODg4ODUwfQ.6-F5XJHcFYYrM0GLUDcMzQsiR5Z7WgTTHnIdF9sOCxo";

/**
 * 跨端存储适配器：
 * - Native: expo-secure-store（加密 keychain，延迟 require 避免 Web 端打包副作用）
 * - Web: localStorage（浏览器本地存储）
 */
const PlatformStorageAdapter = {
  getItem: (key: string): Promise<string | null> => {
    if (Platform.OS === 'web') {
      try {
        return Promise.resolve(
          typeof localStorage !== 'undefined' ? localStorage.getItem(key) : null
        );
      } catch {
        return Promise.resolve(null);
      }
    }
    const SecureStore = require('expo-secure-store');
    return SecureStore.getItemAsync(key);
  },
  setItem: (key: string, value: string): Promise<void> => {
    if (Platform.OS === 'web') {
      try {
        if (typeof localStorage !== 'undefined') localStorage.setItem(key, value);
      } catch {
        // localStorage 满了或隐私模式，忽略
      }
      return Promise.resolve();
    }
    const SecureStore = require('expo-secure-store');
    return SecureStore.setItemAsync(key, value);
  },
  removeItem: (key: string): Promise<void> => {
    if (Platform.OS === 'web') {
      try {
        if (typeof localStorage !== 'undefined') localStorage.removeItem(key);
      } catch {
        // ignore
      }
      return Promise.resolve();
    }
    const SecureStore = require('expo-secure-store');
    return SecureStore.deleteItemAsync(key);
  },
};

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: PlatformStorageAdapter,
  },
});
